backend/src/main/java/com/digginroom/digginroom/controller/GlobalExceptionHandler.java
backend/src/main/java/com/digginroom/digginroom/controller/RoomController.java
backend/src/main/java/com/digginroom/digginroom/controller/dto/RoomResponse.java
backend/src/main/java/com/digginroom/digginroom/domain/MediaSource.java
backend/src/main/java/com/digginroom/digginroom/domain/MediaType.java
backend/src/main/java/com/digginroom/digginroom/domain/Room.java
backend/src/main/java/com/digginroom/digginroom/exception/MediaSourceException.java
backend/src/main/java/com/digginroom/digginroom/exception/RoomException.java
backend/src/main/java/com/digginroom/digginroom/repository/RoomRepository.java
backend/src/main/java/com/digginroom/digginroom/service/RoomService.java
backend/src/test/java/com/digginroom/digginroom/domain/MediaSourceTest.java
backend/src/test/java/com/digginroom/digginroom/domain/RoomTest.java
backend/src/test/java/com/digginroom/digginroom/repository/RoomRepositoryTest.java
backend/src/test/java/com/digginroom/digginroom/service/RoomServiceTest.java

- #31 
- 랜덤한 룸 탐색 기능 구현
- 룸이 아예 없을 시 500 에러 반환
- 작업 내용 테스트 코드 작성
- full-scan을 통해 모든 룸 조회 후, 랜덤으로 **하나** 선택
- 구현과 코드가 간단.
- 페이징을 통한 랜덤 룸 **하나** 선택
- 성능을 조금 고려한 선택

feat: 룸 탐색 기능을 구현한다.

---

backend/.gitignore
backend/src/main/java/com/digginroom/digginroom/controller/GlobalExceptionHandler.java
backend/src/main/resources/logback-spring.xml

- resolved: #89 
- 세부 예외 처리 구현
- 예상하지 못하는 예외 처리 구현
- 서버 에러만 로깅하도록 리팩터링
- 예외 핸들러 메서드 명 통일
- `Logback`을 사용한 Rolling 구현
- `backend/log` 하위 디렉터리에 로그 파일 생성 
- 예외 핸들러 반환 시간과 서버 로그와의 미세한 시간 차이가 있습니다.

feat: 세부 예외 처리 및 Rolling 을 구현한다. 

---

backend/src/main/java/com/digginroom/digginroom/domain/SubGenreConverter.java
backend/src/main/java/com/digginroom/digginroom/domain/Track.java
backend/src/main/java/com/digginroom/digginroom/exception/SubGenreConvertingException.java
backend/src/main/resources/data.sql
backend/src/test/java/com/digginroom/digginroom/domain/TrackTest.java

- #135 
- 트랙 도메인을 구현한다
- 초기 데이터를 삽입한다. (7개, 후속 작업용 샘플)
- `AttributeConverter`를 사용한 서브 장르 영속화 방식 지정
- 추천은 슈퍼장르로 발생하므로 서브 장르는 테이블로 분리할 만큼 중요한 정보가 아님
- 수정, 삭제, 개별조회 등의 행위가 현재 발생하지 않음
- JSON 형식으로 저장
- 음악 제목에 `,` 가 존재할 수 있다.
- `,`, `|` 등 특정 문자를 사용하는 것보다는, '표준 데이터 표현 방식' 인 JSON을 사용하면 특수문자로부터 자유로워질 수 있다.
|객체 설계|스키마|
|---|---|
|![Image](https://github.com/woowacourse-teams/2023-diggin-room/assets/39221443/c1c6c0e6-cf9c-46f2-894c-abe61f5c7cac)|![Image](https://github.com/woowacourse-teams/2023-diggin-room/assets/39221443/9ea3d55a-e4a2-424e-80b0-652eafae4216)|
- 같은 아티스트의 같은 제목은 같은 곡으로 취급한다.
- 같은 아티스트의 어떤 두 곡이 한글자라도 다르다면 다른 곡으로 취급한다.

feat: 트랙 도메인 구현 및 초기 데이터 삽입

---

backend/src/main/java/com/digginroom/digginroom/controller/RoomController.java
backend/src/main/java/com/digginroom/digginroom/domain/Member.java
backend/src/main/java/com/digginroom/digginroom/exception/RoomException.java
backend/src/main/java/com/digginroom/digginroom/service/RoomService.java
backend/src/test/java/com/digginroom/digginroom/controller/RoomControllerTest.java
backend/src/test/java/com/digginroom/digginroom/service/RoomServiceTest.java

- Resolved: #111 
- 싫어요 기능을 개발한다.
- 이미 스크랩을 한 뒤에 싫어요를 할 때에는 예외가 발생하도록 변경
- 이미 싫어요를 한 뒤에 스크랩을 할 때에는 예외가 발생하도록 구현
- 이미 싫어요를 한 뒤에 싫어요를 할 떄에는 예외가 발생하도록 구현
- 싫어요 취소 기능을 개발한다.
- 싫어요 하지 않은 룸에 싫어요 취소 요청시 예외가 발생하도록 구현
- endpoint 변경
- /scrap -> /room/scrap
- /unscrap -> /room/unscrap
- /dislike -> /room/dislike
- 추후 스크랩, 싫어요 관련 엔티티 분리 고려

feat: 싫어요 기능을 개발한다.

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml

- #183 
- 배포 스크립트 중 'pgrep -f' 에서 exit code 1(오류) 발생 
- `DigginRoom-xxx.jar`에 해당하는 프로세스를 찾지 못했기 때문
해당 프로세스를 찾지 못해도 스크립트가 정상적으로 0을 반환하도록 설정
[참고한 자료](https://stackoverflow.com/questions/73066461/github-actions-why-an-intermediate-command-failure-in-shell-script-would-cause)
<br/>

fix: 배포 스크립트 오류를 해결한다

---

backend/src/main/java/com/digginroom/digginroom/domain/DislikeRooms.java
backend/src/main/java/com/digginroom/digginroom/domain/Member.java
backend/src/main/java/com/digginroom/digginroom/exception/RoomException.java
backend/src/main/java/com/digginroom/digginroom/service/RoomService.java
backend/src/test/java/com/digginroom/digginroom/controller/MemberJoinControllerTest.java
backend/src/test/java/com/digginroom/digginroom/controller/RoomControllerTest.java
backend/src/test/java/com/digginroom/digginroom/domain/MemberTest.java
backend/src/test/java/com/digginroom/digginroom/repository/MemberRepositoryTest.java
backend/src/test/java/com/digginroom/digginroom/service/RoomServiceTest.java

- #196 
- 스크랩을 할 때 그 룸이 이미 스크랩 되어 있으면 예외
- 스크랩 취소를 할 때 그 룸이 스크랩 되어 있지 않으면 예외
- 스크랩을 할 때 그 룸이 싫어요 되어있어도 가능하다.
- 스크랩을 할 때 가중치가 올라간다.
- 스크랩을 취소할 때 가중치가 복구된다.
- 싫어요는 여러번 할 수 있다.
- 하나의 룸에 대한 각 싫어요 마다 가중치를 매번 줄여준다.
- 싫어요 취소는 여러번 할 수 있다.
- 하나의 룸에 대한 싫어요 취소마다 가중치를 매번 복구한다.
- 싫어요 취소를 할 때 그 룸이 싫어요 되어 있지 않으면 예외
- 싫어요 할 때 그 룸이 이미 스크랩되어있어도 가능하다.
`Member` 에서 스크랩 목록 및 싫어요 목록을 가져올때 List형식으로 반환하도록 수정

feat: 싫어요 정책 수정사항을 반영

---

backend/src/main/java/com/digginroom/digginroom/exception/OAuthResolverException.java
backend/src/main/java/com/digginroom/digginroom/service/GoogleUsernameResolver.java
backend/src/test/java/com/digginroom/digginroom/service/GoogleUsernameResolverTest.java

- #214 
- 인증 예외를 두 가지로 분리한다.
a. Id Token 자체가 잘못된 경우 (클라이언트 측 오류)
b. 서버가 모종의 이유로 Id Token을 해석할 수 없는 경우 (서버 측 오류)
b의 경우는 인증 과정 상 크리티컬한 문제이므로 별도로 분리하였음.
<br/>

refactor: 소셜 로그인 인증 예외를 리팩토링한다

---

backend/src/main/java/com/digginroom/digginroom/controller/MemberLoginController.java
backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberLoginResponse.java
backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
backend/src/test/java/com/digginroom/digginroom/service/MemberServiceTest.java

- #213
- **PR 대상: #224**
- 기존 브랜치 `feature/213` 에 머지할 내용입니다.
- 로그인 API에 취향정보 수집되었는지 여부 추가
POST /login, /login/google
RESPONSE
```json
{
"memberId": 1
"hasFavorite": false
}
```
<br/>

feat: 로그인 응답에 취향정보 수집되었는지 여부 추가

---

backend/src/main/java/com/digginroom/digginroom/controller/dto/TrackResponse.java
backend/src/main/java/com/digginroom/digginroom/domain/Track.java
backend/src/main/resources/db/migration/V3__track_description_added.sql
backend/src/test/java/com/digginroom/digginroom/controller/TestFixture.java
backend/src/test/java/com/digginroom/digginroom/domain/TrackTest.java

- #220 
- Track 도메인에 Description 필드 추가
- Track Response에 Description 필드 추가
- 테스트 코드에 Description 추가
- Flyway V3 파일 생성
기존 Track 데이터(_data.sql_)에 Description이 없을 경우를 대비해서 Default 를 `" "` 으로 주었습니다.

feat: 트랙에 음악 설명 필드 추가

---

backend/src/main/java/com/digginroom/digginroom/config/OpenApiConfig.java

- #229
Try it out 기능 사용을 위해 서버 주소 명시, 없으면 Mixed Content 오류 (HTTPS -> HTTP로 요청하기 때문)
<br/>

fix: API문서에 서버 주소 명시

---

android/app/build.gradle
android/app/proguard-rules.pro

- #248 
- ProGuard 룰 추가
```
-dontnote retrofit2.Platform
-keepattributes Signature
-keepattributes Exceptions
-dontwarn okio.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
**[] $VALUES;
public *;
}
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
```
```
buildTypes {
debug {
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
}
release {
minifyEnabled true
proguardFiles …
```

feat: 난독화 적용

---

backend/src/main/java/com/digginroom/digginroom/controller/MemberOperationController.java
backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberDetailsResponse.java
backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberLoginResponse.java
backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
backend/src/test/java/com/digginroom/digginroom/controller/MemberArgumentResolverTest.java
backend/src/test/java/com/digginroom/digginroom/controller/MemberOperationControllerTest.java
backend/src/test/java/com/digginroom/digginroom/service/MemberServiceTest.java

- #234 
- 사용자 정보를 가져오는 기능을 구현
- `memberId`, `username`, `hasFavorite `전달
- <img width="684" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/39221443/5af360a8-7f73-419c-88fb-c2ca9ae964b9">
- 세션 아이디를 검증하는 테스트 구현(`MemberArgumentResolverTest`)

feat: 사용자 정보를 가져온다

---

backend/src/main/java/com/digginroom/digginroom/admin/controller/UploadController.java
backend/src/main/java/com/digginroom/digginroom/controller/CommentController.java
backend/src/main/java/com/digginroom/digginroom/controller/dto/CommentResponse.java
backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
backend/src/main/java/com/digginroom/digginroom/service/RoomService.java

- #255 
댓글 API(조회, 등록, 수정)에 요청 유저가 해당 댓글의 주인인지 boolean 타입 필드 추가

feat: 댓글 조회 API에 자신의 댓글 여부를 추가

---

backend/src/main/java/com/digginroom/digginroom/admin/controller/UploadController.java
backend/src/main/java/com/digginroom/digginroom/admin/controller/dto/UploadRequest.java
backend/src/main/resources/templates/uploadForm.html

- #306 
- 룸에 대한 업로드가 성공적으로 이루어지면 기존 선택한 슈퍼장르 유지
- 나머지 필드에 대해서는 입력란을 초기화
- 우측 하단에 업로드 성공 문구 출력
- 기존 각 필드의 필수값, 최대값을 넘길 시 프론트 단에서 1차적으로 경고메시지 출력 후 요청 중단
- 실제 서버에서 필수 값 및 글자수 검증 실패 시 우측 하단에 400 문구 출력
- 다른 이유로 (중복 노래 추가 혹은 서버 장애 등) 업로드 실패 시 우측 하단에 500 문구 출력
- 현재 프론트 페이지에 `<script>` 태그안에 자바스크립트 코드가 존재합니다.
- 처음에는 별도의 파일로 분리를 고려했습니다. 
- 단, 하나의 자바스크립트 파일을 서빙하기 위해서 스프링단에 `addResouceHandler` 를 오버라이드 해야하는 점이 있습니다.
- 하나의 파일만을 위해서 별도의 핸들러를 넣는것이 과하다고 생각해서 일단은 `<script>` 태그 안에 js 코드를 넣어두었습니다.
현재 룸 추가 요청 시 요청한 타이틀과 가수가 이미 데이터베이스에 있는 경우 두 값이 복합키가 걸려있으므로 예외가 발생합니다.
현재 급한 것은 아니기 때문에 리팩터링 사항에 추가 후 추후 해당 검증 기능을 추가할 필요가 있습니다.

refactor: 룸 업로드 페이지 리팩터링

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/digginroom/digginroom/data/datasource/local/TokenLocalDataSource.kt
android/app/src/main/java/com/digginroom/digginroom/data/repository/DefaultTokenRepository.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingActivity.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingCategoryAdapter.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingCategoryDetailViewHolder.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingCategoryDetailsAdapter.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingState.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingViewHolder.kt
android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingViewModel.kt
android/app/src/main/java/com/digginroom/digginroom/model/SettingCategoryDetailModel.kt
android/app/src/main/java/com/digginroom/digginroom/model/SettingCategoryModel.kt
android/app/src/main/res/drawable/ic_logout.xml
android/app/src/main/res/drawable/ic_withdrawal.xml
android/app/src/main/res/layout/activity_setting.xml
android/app/src/main/res/layout/item_setting.xml
android/app/src/main/res/layout/item_setting_detail.xml
android/app/src/main/res/values/strings.xml
android/domain/src/main/java/com/digginroom/digginroom/repository/TokenRepository.kt

- #336 
로그아웃 기능 구현 완료
현재 설정화면에 들어가는 설정 종류들은 이런 계층 구조를 가지고 있습니다.
* SettingCategoryModel
* SettingDetailCategoryModel
리사이클러뷰도 SettingCategoryModel에 대한 리사이클러뷰가 있고 해당 리사이클러뷰의 뷰홀더 안에 SettingDetailCategoryModel들이 표시되는 리사이클러뷰가 존재합니다.
ex) 
* 계정
* 로그아웃
* 회원탈퇴(추가 예정)
* 기타 기능
* 피드백
각 SettingDetailCategoryModel에 해당하는 이벤트가 있을 것인데 이 이벤트를 어떤 방식으로 전해주어야 좋은 구조가 나올지 잘 모르겠습니다. 만약 SettingLisetener로 리사이클러뷰에 전해주게 된다면 각 이벤트에 따라 Model에 매핑하는 과정도 번거로울 것 같아서 현재는 Model을 초기화하는 시점에서 이벤트를 Model의 property로 전해주고 있습니다. 좋은 의견이 있으시면 말해주세요~

feat: 로그아웃 기능을 구현한다.

---

android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomActivity.kt
android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomViewModel.kt
android/app/src/main/java/com/digginroom/digginroom/feature/scrap/activity/ScrapListActivity.kt

- #329 
스크랩 화면에서 스크랩을 해제하는 경우 룸 화면으로 돌아왔을 때 반영이 되지 않는 버그가 있었습니다
그래서 스크랩 화면에서 업데이트된 스크랩 정보를 룸 화면의 이미 캐싱되어있는 룸들에 어떻게 적용해줄까 고민하다가 
[registerForActivityResult](https://developer.android.com/training/basics/intents/result) 를 이용하여 ScrapListActivity -> RoomActivity 로 돌아올 때 최신 스크랩 룸들 결과를 가지고 돌아오도록 구현하였습니다!
이 방법이 괜찮은건지 모르겠어서 혹시 더 나은 방법 아신다면 말씀해주세요~!
<br/>

스크랩 해제 후 메인으로 돌아오면 아이콘 변경되지 않는 버그 해결

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
backend/build.gradle
backend/src/main/java/com/digginroom/digginroom/DigginRoomApplication.java
backend/src/main/java/com/digginroom/digginroom/exception/PlayListException.java
backend/src/main/java/com/digginroom/digginroom/playlist/controller/PlayListController.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/GoogleAccessTokenClient.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/GoogleOAuthConfig.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/GooglePlayListClient.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/dto/GoogleAccessTokenRequest.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/dto/GoogleAccessTokenResponse.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/dto/YouTubePlayListRequest.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/dto/YouTubePlayListResponse.java
backend/src/main/java/com/digginroom/digginroom/playlist/infra/dto/YoutubePlayListItemRequest.java
backend/src/main/java/com/digginroom/digginroom/playlist/service/GoogleAuthService.java
backend/src/main/java/com/digginroom/digginroom/playlist/service/PlayListService.java
backend/src/main/java/com/digginroom/digginroom/playlist/service/dto/PlayListRequest.java
backend/src/main/java/com/digginroom/digginroom/playlist/service/dto/PlayListResponse.java
backend/src/main/resources/application.yml

#364
- insertPlayListItems 요청이 오래걸려서 비동기로 요청을 보내려고 시도했으나 
유튜브 측에서 insert 작업도중에 새로운 insert 작업이 들어오면 409를 리턴해서 동기로 작업했습니다.
- webclient를 사용한 이유는 일단 비동기 처리를 염두해두고 사용한거긴한데, spring에서도 webclient를 권장해서 유지했습니다
> NOTE: As of 5.0 this class is in maintenance mode, with only minor requests for changes and bugs to be accepted going forward. Please, consider using the org.springframework.web.reactive.client.WebClient which has a more modern API and supports sync, async, and streaming scenarios.
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
infra와 service 패키지 코드를 중점적으로 보면 좋을것같고
설정 파일들 실수가 있는지 한번씩 확인하면 좋을듯합니다.

재생목록 추출 기능 개발

---

android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/dialog/CommentDialog.kt

- #387 
- 기존에 by lazy 를 사용하여 ViewModel 초기화했던 방식을 선언과 동시에 초기화해주도록 수정 
<br/>

댓글 포스트 안되는 문제 해결

---

android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/dialog/BottomFixedItemBottomSheetDialog.kt
android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/dialog/CommentDialog.kt
android/app/src/main/res/layout/dialog_comment_bottom_placed_item_layout.xml
android/app/src/main/res/layout/dialog_comment_layout.xml
android/app/src/main/res/layout/item_room_info.xml

- #399 
- editText 와 다이얼로그 텍스트에 다크모드를 적용
- item_room_info 레이아웃 누락된 요소(그림자 및 마진값) 적용
- 뷰 계층 구조를 정리
- 필요한 RecyclerView 에 setHasFixedSize 를 적용
<br/>

댓글창에 다크모드 적용 및 뷰 성능 개선

---

backend/src/main/resources/application-local.yml

<br/> #415 
binding parameter log를 확인할 수 없는 문제 해결
```yaml
logging:
level:
org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
jpa:
properties:
hibernate:
format_sql: true
show-sql: true
```
이전 미션에서 위와 같이 application.yml을 구성했을때 
```yaml
Hibernate: 
select
ordertable0_.id as id1_5_0_,
ordertable0_.empty as empty2_5_0_,
ordertable0_.number_of_guests as number_o3_5_0_,
ordertable0_.table_group_id as table_gr4_5_0_,
tablegroup1_.id as id1_7_1_,
tablegroup1_.created_date as created_2_7_1_ 
from
order_table ordertable0_ 
left outer join
table_group tablegroup1_ 
on ordertable0_.table_group_id=tablegroup1_.id 
where
ordertable0_.id=?
2023-10-24 14:18:22.765 TRACE 66299 --- [    Test worker] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [9]
```
위와 같이 …

fix: binding parameter log를 확인할 수 없는 문제 해결
