- .github/ISSUE_TEMPLATE/bug_report.yml
[여기](https://github.com/woowacourse-teams/2023-diggin-room/blob/028fadf13f21b179a9d38787ebc6e61e6b088d8b/.github/ISSUE_TEMPLATE/bug_report.yml)에서 확인가능해요~
> chore: 버그 제보 이슈 템플릿

- android/app/build.gradle
- #19
build.gradle에 데이터 바인딩 설정 추가
pr closed
> chore: 데이터 바인딩 설정

- backend/build.gradle
- backend/src/main/java/com/digginroom/digginroom/controller/GlobalExceptionHandler.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/ErrorResponse.java
- backend/src/main/java/com/digginroom/digginroom/exception/ErrorCode.java
- backend/src/test/java/com/digginroom/digginroom/controller/ControllerTest.java
- backend/src/test/java/com/digginroom/digginroom/controller/GlobalExceptionHandlerTest.java
- resolve: #26 
404 에러 템플릿 구현
<br/>
> feat: 에러 템플릿 구현

- backend/src/main/java/com/digginroom/digginroom/controller/GlobalExceptionHandler.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/ErrorResponse.java
- backend/src/main/java/com/digginroom/digginroom/exception/DigginRoomException.java
- backend/src/main/java/com/digginroom/digginroom/exception/ErrorCode.java
- backend/src/main/java/com/digginroom/digginroom/exception/RoomException.java
> refactor: 커스텀 예외를 수정한다

- backend/src/main/java/com/digginroom/digginroom/exception/RoomException.java
> refactor: 부모 예외를 추상 클래스로 수정

- backend/src/main/java/com/digginroom/digginroom/controller/MemberController.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberDuplicationResponse.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberRequest.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberSaveRequest.java
- backend/src/main/java/com/digginroom/digginroom/domain/Member.java
- backend/src/main/java/com/digginroom/digginroom/exception/MemberException.java
- backend/src/main/java/com/digginroom/digginroom/repository/MemberRepository.java
- backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
- backend/src/test/java/com/digginroom/digginroom/controller/GlobalExceptionHandlerTest.java
- backend/src/test/java/com/digginroom/digginroom/controller/MemberControllerTest.java
- backend/src/test/java/com/digginroom/digginroom/controller/dto/MemberSaveRequestTest.java
- backend/src/test/java/com/digginroom/digginroom/service/MemberServiceTest.java
- #46
- 회원가입 기능 구현
- 회원 도메인 구현
<br/>
> feat: 기본적인 회원가입 기능을 구현한다.

- backend/src/main/java/com/digginroom/digginroom/controller/MemberController.java
- backend/src/main/java/com/digginroom/digginroom/domain/Member.java
- backend/src/main/java/com/digginroom/digginroom/exception/MemberException.java
- backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
- backend/src/test/java/com/digginroom/digginroom/controller/MemberControllerTest.java
- backend/src/test/java/com/digginroom/digginroom/controller/dto/MemberSaveRequestTest.java
- backend/src/test/java/com/digginroom/digginroom/service/MemberServiceTest.java
- #54 
feat: 유저를 조회하는 기능을 구현한다.
<br/>
> feat: 유저를 조회하는 기능을 구현한다.

- .github/workflows/gradle.yml
<br/> #58 
<br/> `backend` 브랜치에 대한 PR에 CI 적용
<br/>
> chore: ci 적용

- backend/src/main/java/com/digginroom/digginroom/controller/RoomController.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/RoomRequest.java
- backend/src/test/java/com/digginroom/digginroom/controller/RoomControllerTest.java
> feat: 룸 스크랩, 취소 엔드포인트

- .github/workflows/CD.yml
- .github/workflows/cd.yml
- #92 
- self hosted runner 설정 
- 배포 스크립트 작성
> feat: 배포 자동화를 한다.

- backend/src/main/java/com/digginroom/digginroom/config/LogFilter.java
- #98 
- 요청과 응답에 대한 로깅을 구현한다.
<br/>
> feat: 요청-응답 로깅 구현

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- #102 
프로덕션 서버 배포 스크립트 작성 
<br/>
> feat: 프로덕션 서버 배포 자동화

- android/app/src/main/java/com/digginroom/digginroom/views/bindingAdapter/RoomPagerBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/HorizontalScrollPager.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/RoomPager.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/ScrollPager.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/VerticalScrollPager.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roomview/YoutubeRoomPlayer.kt
- android/app/src/main/res/layout/activity_room.xml
- #72 
- RoomPager에서 RoomRepository의 Room들을 받아와 리사이클링시 캐싱후 미리 재생
- RoomPager와 RoomRecylcer, ScrollPager 분리
<br/>
> RoomPager에서 RoomRepository의 Room들을 받아와 리사이클링시 캐싱후 미리 재생

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- #102 
`RUNNER_TRACKING_ID=""` 사용해 프로세스가 정리되지 않도록 설정
<br/>
> fix: 배포 스크립트 오류

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- backend/src/main/resources/application-develop.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-production.yml
- backend/src/main/resources/application.yml
- #119 
- [작업 사항 노션 정리](https://digginroom.notion.site/BE-40c227923a194745bc44c46c451bf8f9?pvs=4)
- 환경 별 설정 분리
- Github Actions 스크립트 수정 (CD)
- Github Actions 시크릿 등록
> 배포 환경별 설정을 분리한다

- android/app/build.gradle
- android/app/src/main/java/com/digginroom/digginroom/viewmodels/RoomViewModel.kt
- android/app/src/main/java/com/digginroom/digginroom/views/activity/RoomActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/views/bindingAdapter/RoomPlayerBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/RoomPager.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roompager/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roomview/RoomPlayerThumbnail.kt
- android/app/src/main/java/com/digginroom/digginroom/views/customview/roomview/YoutubeRoomPlayer.kt
> 룸 로딩시 썸네일 표시, 재생 오류 수정

- android/app/src/main/java/com/digginroom/digginroom/data/repository/DefaultRoomRepository.kt
- android/app/src/main/java/com/digginroom/digginroom/logging/CommonLogger.kt
- android/app/src/main/java/com/digginroom/digginroom/logging/ConsoleLogger.kt
- android/app/src/main/java/com/digginroom/digginroom/logging/DefaultLogResult.kt
- android/app/src/main/java/com/digginroom/digginroom/logging/FirebaseLogger.kt
- android/app/src/main/java/com/digginroom/digginroom/logging/LogResultUtil.kt
- android/domain/src/main/java/com/digginroom/digginroom/logging/LogLevel.kt
- android/domain/src/main/java/com/digginroom/digginroom/logging/LogMessage.kt
- android/domain/src/main/java/com/digginroom/digginroom/logging/LogResult.kt
- android/domain/src/main/java/com/digginroom/digginroom/logging/Logger.kt
- android/domain/src/main/java/com/digginroom/digginroom/repository/RoomRepository.kt
> feat: Logger와 LogResult 구현

- android/app/src/main/java/com/digginroom/digginroom/feature/room/bindingadapter/RoomPagerBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/bindingadapter/RoomPlayerBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/PagingOrientation.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/RoomPager.kt
- android/app/src/main/res/layout/activity_room.xml
> feat: RoomPager에서 RoomPosition, Orientation 지정 가능

- backend/src/main/java/com/digginroom/digginroom/controller/dto/RoomResponse.java
- backend/src/main/java/com/digginroom/digginroom/controller/dto/TrackResponse.java
- backend/src/main/java/com/digginroom/digginroom/service/RoomService.java
- backend/src/test/java/com/digginroom/digginroom/controller/RoomControllerTest.java
- #161 
- 룸 추천할 때 트랙 정보 포함
200 OK
```json
{
"roomId" : 1,
"videoId" : "xxxxxxxx",
"isScrapped" : true
"track" : {
"title" : "좋은날",
"artist" : "아이유",
"superGenre" : "ROCK"
}
}
```
> feat: 룸 추천시 트랙 정보 포함한다.

- android/app/src/main/java/com/digginroom/digginroom/feature/room/bindingadapter/RoomInfoBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/DefaultShowRoomInfoListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/RoomInfoView.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/ShowRoomInfoListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/TrackInfoDialog.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/navigator/DefaultRoomNavigator.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/navigator/RoomNavigator.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/RoomPager.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/navigator/RoomNavigator.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/scraptoggle/ScrapToggle.kt
- android/app/src/main/res/layout/room_info.xml
> feat: RoomPager에서 첫 번째, 마지막 룸일때 스크롤을 방지한다

- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/TrackInfoDialog.kt
- android/app/src/main/res/layout/dialog_track_info_layout.xml
- android/app/src/main/res/values/strings.xml
> feat: 룸 세부 설명에 장르 정보 추가

- android/app/src/main/java/com/digginroom/digginroom/data/datasource/remote/RoomRemoteDataSource.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomViewModel.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/scraptoggle/ScrapToggle.kt
- android/app/src/main/res/layout/room_info.xml
- #190 
- 스크랩 삭제 요청 성공 코드가 200임을 반영
- 스크랩/스크랩 삭제 성공 시 room 정보 업데이트 후, 화면에도 이 정보가 반영되도록 수정
<br/>
> fix: room 스크랩 정보 업데이트 시 스크랩 버튼에 반영되도록 수정

- backend/src/main/resources/db/migration/V1__create_initial_scheme.sql
- backend/src/main/resources/db/migration/V3__room_scrap_count_added.sql
- #222 
room 테이블에 scrap_count이 추가되지 않는 문제 해결
flyway에서는 이전 버전을 수정해도 변경사항을 반영하지않음
<br/>
> fix: room 테이블에 scrap_count이 추가되지 않는 문제 해결

- android/app/src/main/java/com/digginroom/digginroom/data/di/RemoteDataSourceProvider.kt
> CommentRepository 에서 TokenRetrofit 사용하도록 수정

- android/app/src/main/java/com/digginroom/digginroom/data/datasource/local/TokenLocalDataSource.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/RoomPager.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/scrollpager/HorizontalScrollPager.kt
> fix: 룸 탐색시 다시 navigate 하는 오류 수정

- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/bindingadapter/RoomPagerBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/RoomPager.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/scrollpager/HorizontalScrollPager.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/scrollpager/ScrollPager.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/scrollpager/VerticalScrollPager.kt
- android/app/src/main/res/layout/activity_room.xml
- android/app/src/main/res/layout/activity_scrap_room.xml
- #250 
- 스크랩 리스트에서 룸 클릭시 흰 화면만 뜨는 오류
- 소리가 재생되지 않는 오류
- 마지막 룸 도달시 더 이상 스크롤 되지 않도록
- 0번째, 마지막 + 1번째 다른 룸 표시되는 오류
- 다른 액티비티 갔을 때 재생되는 오류
<br/>
> 스크랩 리스트에서 룸 클릭시 흰 화면만 뜨는 오류를 수정한다

- android/app/src/main/java/com/digginroom/digginroom/data/entity/CommentResponse.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentDialogBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/CommentEventListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/DefaultCommentEventListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/result/PostCommentResultListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
- android/app/src/main/java/com/digginroom/digginroom/model/TrackModel.kt
- android/app/src/main/java/com/digginroom/digginroom/model/mapper/CommentMapper.kt
- android/app/src/main/java/com/digginroom/digginroom/model/mapper/TrackMapper.kt
- android/app/src/main/res/layout/dialog_track_info_layout.xml
- android/app/src/main/res/values/strings.xml
- android/domain/src/main/java/com/digginroom/digginroom/model/room/Track.kt
> 댓글 수정 완료 시 이벤트 바뀌도록 구현

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- #258 
디렉토리 복사후에 스프링을 실행하도록 변경
<br/>
> fix: 디렉토리 복사후에 스프링을 실행하도록 변경

- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/RoomInfoView.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/RoomPager.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
> fix: 스크랩 룸의 마지막 스크랩을 선택했을 때 크래시

- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
> feat: 광고 제거

- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentDialogBindingAdapter.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentState.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModel.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/DeleteCommentAlertDialog.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/CommentEventListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/DefaultCommentEventListener.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/result/DefaultShowCommentMenuListener.kt
- android/app/src/main/java/com/digginroom/digginroom/model/CommentModel.kt
- android/app/src/main/java/com/digginroom/digginroom/model/mapper/CommentMapper.kt
- android/app/src/main/res/layout/dialog_comment_layout.xml
- android/app/src/main/res/layout/item_comment.xml
> 스크랩, 댓글 요청이 완료되지 않으면 또 다시 요청을 보내지 않도록 구현 

- android/app/build.gradle
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roompager/RoomPager.kt
> feat: 버전 업그레이드

- android/app/src/test/java/com/digginroom/digginroom/feature/room/RoomViewModelTest.kt
- android/app/src/test/java/com/digginroom/digginroom/fixture/RoomFixture.kt
> RoomViewModel의 스크랩 기능에 대한 테스트 코드를 작성한다.

- android/app/src/main/java/com/digginroom/digginroom/data/di/RemoteDataSourceProvider.kt
- android/app/src/main/java/com/digginroom/digginroom/data/repository/SampleRoomRepository.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
> feat: 유튜브 영상 화면 꽉 채우기

- backend/src/main/resources/db/migration/V5.5__update_column_provider_from_member.sql
- backend/src/main/resources/db/migration/V5.6__update_column_genre_from_member_genre.sql
- backend/src/main/resources/db/migration/V5.7__update_set_nickname_from_member.sql
> chore: 데이터 베이스 테이블 컬럼 수정

- android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/dialog/CommentDialog.kt
- android/app/src/test/java/com/digginroom/digginroom/feature/room/comment/CommentViewModelTest.kt
> fix: 댓글 State 오류 수정

- android/app/build.gradle
- android/app/src/main/java/com/digginroom/digginroom/data/datasource/remote/AccountRemoteDataSource.kt
- android/app/src/main/java/com/digginroom/digginroom/data/repository/DefaultAccountRepository.kt
- android/app/src/main/java/com/digginroom/digginroom/data/service/AccountService.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/join/JoinActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/login/LoginViewModel.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/dialog/CommentDialog.kt
- android/app/src/main/res/layout/activity_login.xml
- android/app/src/main/res/values/strings.xml
- android/domain/src/main/java/com/digginroom/digginroom/repository/AccountRepository.kt
- #297 
* 게스트 로그인을 구현
* 회원가입 성공시 toast message를 띄운다.
<br/>
> feat: 게스트 로그인을 구현한다.

- .github/workflows/ci-android.yml
- android/di/src/main/java/com/dygames/di/DependencyInjector.kt
> fix: secret 문자열 수정

- backend/src/main/java/com/digginroom/digginroom/controller/MemberLoginController.java
- #350 
소셜 로그인 API 다시 뚫음
main 브랜치까지 배포 한번 진행해야 할 듯
<br/>
> hotfix: 소셜 로그인 api 하위 호환성 확보

- backend/src/main/java/com/digginroom/digginroom/controller/MemberLoginController.java
> hotfix: 소셜 로그인 api 하위 호환성 확보 (#351)

- .github/workflows/ci-dev-db.yml
- #348
(이슈에 자세히 설명되어 있습니다! 상황과 해결한 방법이 적혀있으니 정독을 간곡히 부탁드립니다!!)
- DB CI 개선
실행 로그는 [여기](https://github.com/woowacourse-teams/2023-diggin-room/actions/runs/6430750152/job/17462308882)서 확인이 가능합니다.
> refactor: DB CI 스크립트 개선

- backend/src/main/java/com/digginroom/digginroom/feedback/FeedbackService.java
- backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
- backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
- backend/src/main/java/com/digginroom/digginroom/feedback/dto/FeedbackRequest.java
- backend/src/main/java/com/digginroom/digginroom/feedback/dto/FeedbackResponse.java
- backend/src/main/java/com/digginroom/digginroom/feedback/repository/FeedbackRepository.java
- backend/src/main/resources/db/migration/V6.2__create_table_feedback.sql
- backend/src/test/java/com/digginroom/digginroom/feedback/FeedbackServiceTest.java
- backend/src/test/java/com/digginroom/digginroom/feedback/controller/FeedbackControllerTest.java
- #343 
- 피드백 받기 위한 API 개설
- 피드백 내용, 피드백 작성자 기록
- 기존 패키지와 별도로 생성
- 다른 기능 개발이나 리팩터링에 영향을 주거나 받지 않는다.
> feat: 피드백 창구를 개설한다

- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubePlayerIframe.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubePlayerWebViewClient.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubeRoomPlayer.kt
> feat: 추천 영상 제거

- android/RoomPager/src/main/java/com/dygames/roompager/Adapter.kt
- android/RoomPager/src/main/java/com/dygames/roompager/RoomRecycler.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomPagerAdapter.kt
> feat: Dislike 구현

- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/room/roominfo/RoomInfoEvent.kt
- android/app/src/main/res/layout/item_room_info.xml
- android/app/src/main/res/values/strings.xml
- #367 
- 
```kotlin
getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
```
API 32 이하에서는 카피 성공시 토스트 표시
<br/>
> feat: 곡 정보 클릭시 클립보드에 복사

- android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roomplayer/YoutubePlayerIframe.kt
> feat: 곡 재생 20~60초 사이에 랜덤으로 재생 시작

- .github/workflows/ci-dev-db.yml
> fix: docker volumes이 삭제되지 않는 문제 해결

- backend/src/main/java/com/digginroom/digginroom/playlist/controller/PlayListController.java
- #375
@RestController가 아니어서 swagger가 적용이 안되는 문제가 있음
<br/>
<br/>
> refactor: @Controller->@RestController 변경 및 endpoint 수정

- android/RoomPager/src/main/java/com/dygames/roompager/util/ScreenSizeUtil.kt
- android/app/build.gradle
- #386 
minSdk를 수정
roomPager 화면에 꽉차지 않는 오류를 해결
<br/>
> refactor: minSdk를 수정한다.

- android/app/src/main/res/layout/activity_feedback.xml
- android/app/src/main/res/layout/activity_setting.xml
> refactor: 뒤로가기 버튼 크기를 통일한다.

- android/app/src/main/java/com/digginroom/digginroom/feature/room/RoomActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/tutorial/TutorialFragment.kt
> 튜토리얼 주석 해제 및 스킵 되도록 수정

- android/app/src/main/java/com/digginroom/digginroom/data/entity/PlaylistResponse.kt
- #402 
release 버전에서 플레이리스트 추출이 되지 않는 오류를 해결
<br/>
> fix: release 버전에서 플레이리스트 추출이 되지 않는 오류를 해결한다.

- README.md
> docs: README 페이지를 작성한다.

- .github/workflows/cd-prod.yml
> chore: 무중단 배포 스크립트 Production 적용

- android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingActivity.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingUiState.kt
- android/app/src/main/java/com/digginroom/digginroom/feature/setting/SettingViewModel.kt
- android/app/src/test/java/com/digginroom/digginroom/feature/login/LoginViewModelTest.kt
- android/app/src/test/java/com/digginroom/digginroom/feature/setting/SettingViewModelTest.kt
> refactor: 누락된 테스트 코드 작성
